### ISSUE TITLE
Can it work on OpenJDK.

### ISSUE THREAD

**Issue by lolive** [MarkusBernhardt/proxy-vole#39]
Hello. I try to run a sample code of ProxyVole with the OpenJDK.
And I get this exeption:
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/Structure
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.readIEProxyConfig(IEProxySearchStrategy.java:67)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.getProxySelector(IEProxySearchStrategy.java:38)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:216)
	at toto.Toto.main(Toto.java:22)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Structure
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

Is it possible to run ProxyVole on OpenJDK? How can it be done?

**Comment by MarkusBernhardt** [comment]
Hi. This error means the JRE cannot find the jna-4.5.1.jar in the classpath. Not a problem of proxy-vole.
