### ISSUE TITLE
ProxySearch.getDefaultProxySearch().getProxySelector(); returning null

### ISSUE THREAD

**Issue by andrew-sumner** [MarkusBernhardt/proxy-vole#42]
ProxySearch.getDefaultProxySearch().getProxySelector(); returns null on my MacBook and in Travis (https://travis-ci.org).  

Not sure if this expected behaviour when not behind a proxy in Linux but it doesn't happen in windows.

**Comment by Jebusito** [comment]
Same thing, it doesn't matter if I define strategies or use the default. In my case on windows 10 (1903) and java 8.

**Comment by kipchubett** [comment]
Just encountered this while using IntelliJ IDEA. I haven't investigated this issue further... it's not much of a big deal but I thought it's worth mentioning.
```java
Cannot select using PAC

java.lang.NullPointerException
	at com.github.markusbernhardt.proxy.search.desktop.osx.OsxProxySearchStrategy.getProxySelector(OsxProxySearchStrategy.java:117)
	at com.github.markusbernhardt.proxy.search.desktop.DesktopProxySearchStrategy.getProxySelector(DesktopProxySearchStrategy.java:38)
	at com.github.markusbernhardt.proxy.search.browser.firefox.FirefoxProxySearchStrategy.getProxySelector(FirefoxProxySearchStrategy.java:113)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:222)
	at com.intellij.util.io.IoServiceImpl.getProxySelector(IoServiceImpl.java:19)
	at com.intellij.util.net.NetUtils.getProxySelector(NetUtils.java:223)
	at com.intellij.util.net.IdeaWideProxySelector.selectUsingPac(IdeaWideProxySelector.java:86)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:62)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:215)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:180)
	at com.intellij.util.net.HttpConfigurable.openConnection(HttpConfigurable.java:406)
	at com.intellij.openapi.fileEditor.impl.IdeUiServiceImpl.openHttpConnection(IdeUiServiceImpl.java:128)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:550)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:359)
	at com.android.tools.idea.imports.GMavenIndexRepository$readUrlData$2.process(GMavenIndexRepository.kt:226)
	at com.android.tools.idea.imports.GMavenIndexRepository$readUrlData$2.process(GMavenIndexRepository.kt:71)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at com.android.tools.idea.imports.GMavenIndexRepository.readUrlData(GMavenIndexRepository.kt:225)
	at com.android.tools.idea.imports.GMavenIndexRepository.refreshDiskCache(GMavenIndexRepository.kt:183)
	at com.android.tools.idea.imports.GMavenIndexRepository.refresh(GMavenIndexRepository.kt:132)
	at com.android.tools.idea.imports.GMavenIndexRepository.refreshWithRetryStrategy(GMavenIndexRepository.kt:113)
	at com.android.tools.idea.imports.GMavenIndexRepository.access$refreshWithRetryStrategy(GMavenIndexRepository.kt:71)
	at com.android.tools.idea.imports.GMavenIndexRepository$task$1.run(GMavenIndexRepository.kt:87)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
