### ISSUE TITLE
StackOverflowError during Detection of Proxy from PAC in proxy-vole-20131209 & proxy-vole-1.0.5.jar

### ISSUE THREAD

**Issue by Ashok-Ilanji** [MarkusBernhardt/proxy-vole#65]
I'm getting the below exception while detecting Proxy from PAC file. 

Currently, we are using the proxy-vole_20120920 jar to detect the proxy from PAC file As per current flow, after entering into NashornScriptEngine((Reader reader, ScriptContext ctxt) throws the exception. 

As per this  [link ](https://github.com/MarkusBernhardt/proxy-vole/issues/38), this bug was fixed  proxy-vole-1.0.4.jar and it works but the same exception has occurred in  proxy-vole-1.0.5.jar. Kindly recommend us "which version had a fix for this issue".

[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: javax.servlet.ServletException: java.lang.StackOverflowError|
[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:295)|
[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:170)|
[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)|
[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)|
[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)|
[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: 	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)|
[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)|
[13:42:30:868]|[01-10-2019]|[SYSERR]|[INFO]|[106]|[6c023c5c-8418-49a8-81c1-cf3bc47a6868]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)|

**Comment by gschnepp** [comment]
Proxy-vole 1.0.4 was using a sandboxed version of Mozillas Rhino JavaScript engine intermediately for security reasons by potencially agressive JavaScript in PAC files, while up to proxy-vole 1.0.3 the native Java Nashorn engine was used. Proxy-vole switched back to (a sandboxed version of) Nashorn with 1.0.5 to reduce the dependency footprint.

So it can be that a bug rising with Nashorn engine was indeed fixed with 1.0.4 but is back again with 1.0.5. If you read the other open issues and pull requests you'll find more problems pointing back to Nashorn engine, and my personal favorite is to switch to Rhino again with 1.0.6. Rhino seems to be much more stable than Nashorn, overruling the drawback from the additional dependencies in my eyes.

@MarkusBernhardt: How's about building a new proxy-vole in the next few weeks, with Rhino engine again?

**Comment by gschnepp** [comment]
Markus doesn't answer any issues or pull requests here for nearly a year now. This project is dead, I think. Unfortunately.  :-(
